---
- name: we take swap space used (megabytes)
  shell : free -m | grep Swap | awk '{print $2}'
  register: swap_used
  changed_when: false

- name: Turn off swap
  shell: "swapoff -a"
  when: (swap_used.stdout_lines[0] | int) > 0
# This task disables swap for Kubernetes node (see https://github.com/kubernetes/kubernetes/pull/31996)
- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: (swap_used.stdout_lines[0] | int) > 0